name: CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write            # needed to push to GHCR with GITHUB_TOKEN
    outputs:
      sha_tag: ${{ steps.vars.outputs.SHA_TAG }}
    steps:
      - uses: actions/checkout@v4

      - name: Lowercase owner (for GHCR path)
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR (using GITHUB_TOKEN)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.OWNER_LC }}/uptimechecker
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Expose image tag for deploy
        id: vars
        run: echo "SHA_TAG=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4   # <-- required so files exist in this job

      - name: Show files for deploy (debug)
        run: |
          pwd
          ls -la
          echo "== migrations =="
          ls -la migrations || true

      - name: Copy compose + migrations to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT || 22 }}
          source: |
            ./docker-compose.yml
            ./docker-compose.prod.yml
            ./migrations/**/*.sql
          target: ${{ secrets.PROD_DIR }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT || 22 }}
          script: |
            set -e
            cd ${{ secrets.PROD_DIR }}
            export IMAGE_TAG='${{ needs.build-and-push.outputs.sha_tag }}'
            echo "Using IMAGE_TAG=$IMAGE_TAG"

            # pick whichever compose file is present
            COMPOSE_FILE=docker-compose.yml
            if [ -f docker-compose.prod.yml ]; then COMPOSE_FILE=docker-compose.prod.yml; fi
            echo "Using $COMPOSE_FILE"

            docker compos
