name: CI/CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write            # allow GITHUB_TOKEN to push to GHCR
    outputs:
      sha_tag: ${{ steps.vars.outputs.SHA_TAG }}
    steps:
      - uses: actions/checkout@v4

      - name: Lowercase owner (for GHCR path)
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR (using GITHUB_TOKEN)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.OWNER_LC }}/uptimechecker
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ github.sha }}
            type=sha

      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Expose image tag for deploy
        id: vars
        run: echo "SHA_TAG=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Show files for deploy (debug)
        run: |
          pwd
          ls -la
          echo "== migrations ==" && ls -la migrations || true
          echo "== frontend ==" && ls -la frontend || true
          test -f docker-compose.prod.yml || { echo "docker-compose.prod.yml missing"; exit 1; }

      # --- package only what's needed on the server ---
      - name: Prepare deploy bundle
        run: |
          set -e
          rm -rf bundle
          mkdir -p bundle
          cp docker-compose.prod.yml bundle/
          if [ -d migrations ]; then cp -r migrations bundle/; fi
          if [ -d frontend ]; then cp -r frontend bundle/; fi
          echo "Bundle contents:"
          find bundle -maxdepth 3 -type f -print

      - name: Copy bundle to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT || 22 }}
          source: bundle/**
          target: ${{ secrets.PROD_DIR }}
          strip_components: 1

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT || 22 }}
          script: |
            set -e
            cd ${{ secrets.PROD_DIR }}

            # Select the image tag produced in build job (full commit SHA)
            export IMAGE_TAG='${{ needs.build-and-push.outputs.sha_tag }}'
            echo "Using IMAGE_TAG=$IMAGE_TAG"

            # Login to GHCR (required if your repo/org packages are private)
            echo '${{ github.token }}' | docker login ghcr.io -u '${{ github.actor }}' --password-stdin

            # Pull only registry-backed services (api, db). Frontend will be built locally.
            docker compose -f docker-compose.prod.yml pull api db

            # Build the frontend image locally from ./frontend and start all services
            docker compose -f docker-compose.prod.yml up -d --build --remove-orphans

            # Optional cleanup
            docker image prune -f
